name: AI PR Description

on:
  workflow_dispatch:
  pull_request_target:
    types: [opened]

jobs:
  generate-description:
    runs-on: ubuntu-latest
    steps:
      - name: Generate PR description
        uses: Codium-ai/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
