name: AI PR Description

on:
  workflow_dispatch:
  pull_request_target:
    types: [opened]

jobs:
  generate-description:
    runs-on: ubuntu-latest
    steps:
      - name: Generate PR description
        uses: Codium-ai/pr-agent@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
